[package]
name = "insertion"
version = "0.1.0"
authors = ["Matúš Mrekaj <matus.mrekaj@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
